license:
  name: lgpl
  version: 3
program:
  name: Formula-Analysis-Lib
  description: Library to analyze propositional formulas.
  authors: Sebastian Krieter
  url: https://github.com/skrieter/formula
  year: 2021
